name: Java CI
on:
  push:
    branches: ["master"]
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: mvn install
        run: mvn -B install
      - name: build and push docker image
        run: mvn -B spring-boot:build-image -DskipTests -DDOCKER_REGISTRY_USERNAME=${{secrets.DOCKER_REGISTRY_USERNAME}} -DDOCKER_REGISTRY_PASSWORD=${{secrets.DOCKER_REGISTRY_PASSWORD}} -DDOCKER_REGISTRY_EMAIL=${{secrets.DOCKER_REGISTRY_EMAIL}}
      - name: push deployment files to gitops repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{secrets.TOKEN}}
        with:
          source-directory: 'target/classes/kubernetes'
          destination-github-username: 'amegiab'
          destination-repository-name: 'periodictableservice-argocd-ops'
          user-email: 'amegia@gmail.com'
          target-branch: 'master'